# Generated by Django 4.1.4 on 2022-12-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_geometry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_note',
            name='note_sub',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
